stages:
  - build
  - test
  - deploy
variables:
  NGINX_CONTAINER_NAME: nginx

build:
  stage: build
  script:
    - echo "hello-build stage" > file01.txt
  only:
    - main
  tags:
    - dind
test:
  stage: test
  script:
    - echo "hello-test stage" >> file01.txt
  only:
    - main
  tags:
    - dind

deploy:
  stage: deploy
  script:
    # Pull the latest Nginx Docker image from the specified registry
    - docker pull nginx:latest
    # Run a Docker container named "nginx" using the pulled image
    - docker run -d --name $NGINX_CONTAINER_NAME -p 800:80 nginx:latest
    - echo "hello-build stage" >> file01.txt
  only:
    - main
  tags:
    - dind
